services:
  db:
    image: postgres:18
    container_name: aeroplane_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres_localhost-2026_01_11_16_56_10-dump.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: aeroplane_web
    restart: always
    ports:
      - "5000:5000"
    environment:
      # KLUCZOWA ZMIENNA: Wyłącza buforowanie wyjścia Pythona
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      LOG_SECRET_KEY: ${LOG_SECRET_KEY}
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs 

volumes:
  postgres_data: